### ISSUE TITLE
[meta] swing up of an inverted pendulum using NMPC

### ISSUE THREAD

**Issue by pierfabre** [Armandpl/furuta#66]
- [ ] Litterature review
   - [ ] What model of the system do people usually use? (input is Torque? if yes do they model the motor?
   - [ ] What library do they use? croccodyl? 
   - [ ] what control frequency do they manage to obtain?
- [ ] In simulation
   - [ ] Implement an accurate simulation or improve the existing one if needed
   - [ ] implement an estimator (EKF) to have access to the velocities
   - [ ] perform system id if needed
   - [ ] implement NMPC
   - [ ]

**Comment by pierfabre** [comment]
[Capture vidéo du 04-02-2024 14:54:36.webm](https://github.com/Armandpl/furuta/assets/73385720/f40eeef9-470e-493f-ba22-a1387b21094d)

**Comment by pierfabre** [comment]
# done

![image](https://github.com/Armandpl/furuta/assets/73385720/36b7466c-670e-4f48-812e-df3c0415c2f7)

**Comment by pierfabre** [comment]
# 20250923 - First closed loop swing up on the real robot using NMPC 

## Video

https://github.com/user-attachments/assets/c8737dfd-af30-4cf1-909c-0b0155b555c5

 ## Plots

<img width="2714" height="1762" alt="Image" src="https://github.com/user-attachments/assets/64812715-6f38-4b31-afed-4fea0117a716" />

## Comment

I'm so happy that it's finally working 🚀 

## Next step

Reduce those vibrations 🤖
